name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Train model (artifact)
        run: python src/train.py --data data/raw/house_prices.csv --outdir models
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            models/*
            reports/figures/fit_plot.png
